[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
db_host = postgres
db_port = 5432
db_user = odoo
db_password = False
db_name = False
db_maxconn = 16
workers = 0
max_cron_threads = 1
limit_memory_soft = 402653184
limit_memory_hard = 536870912
limit_time_cpu = 600
limit_time_real = 1200
proxy_mode = True
log_level = info
