# Production override
# ใช้: docker compose -f docker-compose.yml -f docker-compose.prd.yml up -d

services:
  odoo:
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2G

  odoo-db:
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2G

  wordpress:
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M

  wp-db:
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G

  emqx:
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G

  nodered:
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M

  n8n:
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G

  n8n-db:
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M

  redis:
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
