# Production override
# ใช้: docker compose -f docker-compose.yml -f docker-compose.prd.yml up -d

services:
  airflow-webserver:
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G

  airflow-scheduler:
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G

  airflow-worker:
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "2.0"
          memory: 2G

  db:
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G

  redis:
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
