#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname postgres <<-EOSQL
    CREATE USER ${ODOO_DB_USER} WITH PASSWORD '${ODOO_DB_PASSWORD}';
    CREATE DATABASE odoo OWNER ${ODOO_DB_USER};
    GRANT ALL PRIVILEGES ON DATABASE odoo TO ${ODOO_DB_USER};

    CREATE USER ${KEYCLOAK_DB_USER} WITH PASSWORD '${KEYCLOAK_DB_PASSWORD}';
    CREATE DATABASE keycloak OWNER ${KEYCLOAK_DB_USER};
    GRANT ALL PRIVILEGES ON DATABASE keycloak TO ${KEYCLOAK_DB_USER};

    CREATE USER ${TB_DB_USER} WITH PASSWORD '${TB_DB_PASSWORD}';
    CREATE DATABASE thingsboard OWNER ${TB_DB_USER};
    GRANT ALL PRIVILEGES ON DATABASE thingsboard TO ${TB_DB_USER};
EOSQL

echo "=== All databases created: odoo, keycloak, thingsboard ==="
