# Production override
# ใช้: docker compose -f docker-compose.yml -f docker-compose.prd.yml up -d

services:
  wordpress:
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M

  db:
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G

  redis:
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
